server:
  port: 8081

spring:
  application:
    name: project1

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    preferIpAddress: true

